trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - docs

jobs:
  - job: Windows_Build
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'filePath'
          filePath: 'ci\windows-build.ps1'
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: Release Build"
        inputs:
          PathtoPublish: .\target\release\crom.exe
          ArtifactName: crom-windows
          ArtifactType: Container

  - job: Check_Style
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: |
          set -e
          docker build -t checker -f ci/style.Dockerfile .
          docker run --rm checker

  - job: Linux_Build
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: |
          set -e
          mkdir -p target/x86_64-unknown-linux-musl/release/
          docker build -t musl-builder -f ci/musl.Dockerfile .
          docker run --name musl-build musl-builder
          docker cp musl-build:/home/rust/src/target/x86_64-unknown-linux-musl/release/crom target/x86_64-unknown-linux-musl/release/crom
          docker rm musl-build
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: Release Build"
        inputs:
          PathtoPublish: ./target/x86_64-unknown-linux-musl/release/crom
          ArtifactName: crom-linux
          ArtifactType: Container

  - job: Mac_Build
    pool:
      vmImage: 'macOS-10.13'
    steps:
      - script: |
          set -e
          curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
          $HOME/.cargo/bin/cargo build
          ./target/debug/crom update-version --pre-release release

          $HOME/.cargo/bin/cargo test
          $HOME/.cargo/bin/cargo build --release
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: Release Build"
        inputs:
          PathtoPublish: ./target/release/crom
          ArtifactName: crom-mac
          ArtifactType: Container
  
  - job: Release
    pool:
      vmImage: "ubuntu-16.04"
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    dependsOn:
      - Check_Style
      - Mac_Build
      - Linux_Build
      - Windows_Build
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          downloadType: specific
          downloadPath: $(System.ArtifactsDirectory)/artifacts
      - script: |
          set -e
          cp $SYSTEM_ARTIFACTSDIRECTORY/artifacts/crom-linux/crom ~/crom && chmod +x ~/crom
          ~/crom tag-version --source local,github --ignore-changes
          ~/crom upload-artifacts --root-artifact-path=$SYSTEM_ARTIFACTSDIRECTORY linux mac windows
