trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - docs
      - version.properties
      - Cargo.toml
jobs:
  - job: Windows_Build
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'filePath'
          filePath: 'ci\windows-build.ps1'
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: Release Build"
        inputs:
          PathtoPublish: .\target\release\crom.exe
          ArtifactName: crom-windows
          ArtifactType: Container

  - job: Linux_Build
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: |
          curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
          $HOME/.cargo/bin/rustup target add x86_64-unknown-linux-musl
          sudo apt-get install -y cmake

          $HOME/.cargo/bin/cargo build --target=x86_64-unknown-linux-musl --release
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: Release Build"
        inputs:
          PathtoPublish: ./target/x86_64-unknown-linux-musl/release/crom
          ArtifactName: crom-linux
          ArtifactType: Container

  - job: Mac_Build
    pool:
      vmImage: 'macOS-10.13'
    steps:
      - script: |
          curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
          $HOME/.cargo/bin/cargo test
          $HOME/.cargo/bin/cargo build --release
          pwd
          ls target/release
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: Release Build"
        inputs:
          PathtoPublish: ./target/release/crom
          ArtifactName: crom-mac
          ArtifactType: Container
  
  - job: Release
    pool:
      vmImage: "ubuntu-16.04"
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    dependsOn:
      - Mac_Build
      - Linux_Build
      - Windows_Build
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          downloadType: specific
          downloadPath: $(System.ArtifactsDirectory)/artifacts
      - script: |
          curl --location https://github.com/ethankhall/release-manager/releases/download/v0.1.9/release-manager-linux -o ~/release-manager
          chmod +x ~/release-manager
          sudo apt-get install -y tree
          tree $SYSTEM_ARTIFACTSDIRECTORY
          ~/release-manager github release-and-bump
          ~/release-manager github artifacts \
            crom-windows.exe=$SYSTEM_ARTIFACTSDIRECTORY/artifacts/crom-windows/crom.exe \
            crom-mac=$SYSTEM_ARTIFACTSDIRECTORY/artifacts/crom-mac/crom \
            crom-linux=$SYSTEM_ARTIFACTSDIRECTORY/artifacts/crom-linux/crom