variables:
  crom-version: v0.1.0

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - docs
      - version.properties
      - Cargo.toml

jobs:
  - job: Windows_Build
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'filePath'
          filePath: 'ci\windows-build.ps1'
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: Release Build"
        inputs:
          PathtoPublish: .\target\release\crom.exe
          ArtifactName: crom-windows
          ArtifactType: Container

  - job: Linux_Build
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: |
          curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
          $HOME/.cargo/bin/rustup target add x86_64-unknown-linux-musl
          sudo apt-get install -y cmake musl-tools
          curl --location https://github.com/ethankhall/crom/releases/download/$(crom-version)/crom-linux -o ~/crom && chrom +x ~/crom
          ~/crom update-version --no-snapshot

          $HOME/.cargo/bin/cargo build --target=x86_64-unknown-linux-musl --release
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: Release Build"
        inputs:
          PathtoPublish: ./target/x86_64-unknown-linux-musl/release/crom
          ArtifactName: crom-linux
          ArtifactType: Container

  - job: Mac_Build
    pool:
      vmImage: 'macOS-10.13'
    steps:
      - script: |
          curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
          curl --location https://github.com/ethankhall/crom/releases/download/$(crom-version)/crom-mac -o ~/crom && chrom +x ~/crom
          ~/crom update-version --no-snapshot

          $HOME/.cargo/bin/cargo test
          $HOME/.cargo/bin/cargo build --release
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: Release Build"
        inputs:
          PathtoPublish: ./target/release/crom
          ArtifactName: crom-mac
          ArtifactType: Container
  
  - job: Release
    pool:
      vmImage: "ubuntu-16.04"
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    dependsOn:
      - Mac_Build
      - Linux_Build
      - Windows_Build
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          downloadType: specific
          downloadPath: $(System.ArtifactsDirectory)/artifacts
      - script: |
          cp SYSTEM_ARTIFACTSDIRECTORY/artifacts/crom-linux/crom ~/crom && chrom +x ~/crom
          ~/crom tag-version --source local,github --ignore-changes
          ~/crom upload-artifacts \
            crom-windows.exe=$SYSTEM_ARTIFACTSDIRECTORY/artifacts/crom-windows/crom.exe \
            crom-mac=$SYSTEM_ARTIFACTSDIRECTORY/artifacts/crom-mac/crom \
            crom-linux=$SYSTEM_ARTIFACTSDIRECTORY/artifacts/crom-linux/crom