[package]
name = "crom"
version = "999.9.9-SNAPSHOT"
authors = ["Ethan Hall <ethan@ehdev.io>"]
edition = "2018"

[dependencies]
log = "0.4"
fern = { version = "0.5", features = ["colored"] }
clap = { version = "2.*", features = ["color"] }
colored = "1.6"
git2 = { version = "0.7", default-features = false }
chrono = "0.4"
serde = "1.0"
serde_derive = "1.0"
toml = "0.5"
regex = "1.1"
toml_edit = "0.1"
rust-ini = "0.13"
xmltree = "0.8"
json = "*"
reqwest = { version = "0.9", features = ["rustls-tls"] }
indicatif = "0.11"
mime_guess = "2.0.1"
mime = "0.3.5"
futures = "0.3.3"
url = "2.1"
zip = "0.5"
libflate = "0.1"
tempfile = "3.0"
tar = "0.4"
hyper = "0.12.22"
serde_json = { version = "1.0", features = ["preserve_order"] }

[dev-dependencies]
assert_cmd = "0.11"
tempdir = "0.3"
predicates = "1.0"
mockito = "*"