name: Publish Image

on:
  push:
    branches:
    - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: do-build
        run: |
          mkdir -p target/x86_64-unknown-linux-musl/release/
          docker build . --file Dockerfile --tag crom
          docker run --name crom crom help
          docker cp crom:/usr/bin/crom target/x86_64-unknown-linux-musl/release/crom
          docker rm crom
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: linux-artifacts
          path: target/x86_64-unknown-linux-musl/release/crom

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: -- write-version next-release
      - uses: actions-rs/cargo@v1
        with:
          command: check
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: mac-artifacts
          path: target/release/crom

  release:
    runs-on: ubuntu-latest
    needs:
      - build-linux
      - build-mac
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v1
        with:
          name: mac-artifacts
          path: artifacts/mac
      - uses: actions/download-artifact@v1
        with:
          name: linux-artifacts
          path: artifacts/linux
      - name: Create release
        run: |
          set -eux
          chmod +x artifacts/linux/crom
          artifacts/linux/crom tag next-release --local --github
          artifacts/linux/crom upload latest --artifact-path=./artifacts linux mac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-publish:
    runs-on: ubuntu-latest
    needs:
      - release
    steps:
    - uses: actions/checkout@v1
    - name: login to registry
      run: docker login docker.pkg.github.com --username ethankhall --password ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag crom
    - name: push to registry
      run: |
        VERSION=$(docker run --rm -v $(pwd):/target crom get latest | sed 's/v//g')
        docker tag crom docker.pkg.github.com/ethankhall/crom/cli:$(git rev-parse --short HEAD)
        docker tag crom docker.pkg.github.com/ethankhall/crom/cli:latest
        docker tag crom docker.pkg.github.com/ethankhall/crom/cli:$VERSION
        docker push docker.pkg.github.com/ethankhall/crom/cli:$(git rev-parse --short HEAD)
        docker push docker.pkg.github.com/ethankhall/crom/cli:latest
        docker push docker.pkg.github.com/ethankhall/crom/cli:$VERSION